SELECT *FROM employee WHERE PLACE='MADURAI' ORDER BY AGE;
SELECT * FROM employee WHERE NOT EID=4 OR AGE=28;
SELECT * FROM employee WHERE PLACE IS NULL;
INSERT INTO EMPLOYEE(EID,NAME,AGE)VALUES(6,'HARI',21)
SELECT MIN(AGE) FROM employee WHERE AGE=23 OR PLACE='CHENNAI';
SELECT MAX(AGE) FROM employee;
SELECT COUNT (AGE)
FROM EMPLOYEE
SELECT SUM(AGE)FROM EMPLOYEE;
SELECT AVG(AGE)AS AVERAGE FROM EMPLOYEE;
SELECT * FROM employee WHERE EID BETWEEN 3AND 6;
SELECT AGE FROM EMPLOYEE WHERE PLACE IN('CHENNAI','NULL')
SELECT* FROM EMPLOYEE WHERE PLACE IN('CHENNAI','NULL');
SELECT*FROM employee WHERE PINCODE LIKE'123%'
SELECT*FROM employee WHERE PINCODE LIKE'%78'
SELECT*FROM employee WHERE PINCODE LIKE'1%8'
SELECT*FROM employee WHERE PLACE LIKE 'M_%'
INSERT INTO EMPLOYEE(EID,NAME,AGE,PINCODE)VALUES(7,'RAVI',21,123876)
DELETE FROM employee WHERE EID=6;
SELECT COUNT(EID) 'COUNT',AGE FROM EMPLOYEE GROUP BY AGE HAVING COUNT(EID)<5;
SELECT COUNT(age) 'COUNT',eid FROM EMPLOYEE GROUP BY AGE HAVING COUNT(age)<23;
INSERT INTO EMPLOYEE(EID,NAME,AGE,PINCODE,mark)VALUES(9,'SASI',21,123876,15)
SELECT * FROM employee WHERE MARK=15;
  WHERE NOT MARK=15;
SELECT PLACE FROM EMPLOYEE WHERE PLACE IS NULL; 


SELECT * FROM EMPLOYEE

SELECT * FROM Persons
CREATE TABLE Persons (
    ID int NOT NULL PRIMARY KEY,
    LastName varchar(255) NOT NULL,
    FirstName varchar(255),
    Age int
);
SELECT PERSONS.ID, EMPLOYEE.AGE,PLACE,NAME
FROM EMPLOYEE
INNER JOIN PERSONS ON PERSONS.ID = PERSONS.ID;

SELECT*FROM EMPLOYEE
INNER JOIN PERSONS ON PERSONS.ID = PERSONS.ID;

SELECT NAME,FirstName,LastName,PLACE  FROM EMPLOYEE INNER JOIN Persons ON EMPLOYEE.ID=PERSONS.ID;

SELECT*  FROM EMPLOYEE INNER JOIN Persons ON EMPLOYEE.ID=PERSONS.ID;

SELECT*  FROM EMPLOYEE  INNER JOIN Persons ON EMPLOYEE.AGE=PERSONS.AGE;
SELECT*  FROM EMPLOYEE LEFT JOIN Persons ON EMPLOYEE.AGE=PERSONS.AGE;
SELECT*  FROM EMPLOYEE RIGHT JOIN Persons ON EMPLOYEE.AGE=PERSONS.AGE;
SELECT NAME,FirstName,LastName,PLACE FROM EMPLOYEE FULL JOIN Persons ON EMPLOYEE.AGE=PERSONS.AGE;
INSERT INTO EMPLOYEE(ID,NAME,AGE,PLACE,PINCODE,mark,PHOTO)VALUES(12,'KALAI',21,'MADURAI',123876,15,'')


ALTER TABLE EMPLOYEE DROP COLUMN PHOTO;
ALTER TABLE EMPLOYEE ADD PHOTO [VARCHAR](10);
SELECT  COUNT(AGE) "AGE",ID  FROM EMPLOYEE GROUP BY ID ORDER BY COUNT(AGE);

SELECT 

SELECT * FROM STOCK

SELECT CATEGORY, SUM(QUANITY)   FROM STOCK GROUP BY CATEGORY

SELECT COUNT(PNAME)'count' , CATEGORY FROM STOCK GROUP BY CATEGORY

//HOWMANY EMP ARE WORKING IN EACH DEPT

SELECT DEPT, COUNT(DEPT) FROM EMP GROUP BY DEPT


//WHAT IS THE AVERAGE SALARY OF A DEPT

SELECT DEPT, AVG(SALARY) FROM EMP GROUP BY DEPT


SELECT DEPT, MAX(SALARY)as maxsal FROM EMP GROUP BY DEPT

SELECT DEPT, COUNT(DEPT) FROM EMP GROUP BY DEPT
SELECT DEPT, CITY, COUNT(CITY) AS "TOAL EMP" FROM EMP GROUP BY DEPT, CITY


SELECT ENAME, LEN(ENAME) FROM EMP

SELECT ALL *
FROM EMPLOYEE
WHERE AGE>23;
SELECT HOST_NAME();
SELECT SUSER_SID() "ID";  
SELECT USER_ID();
SELECT DB_ID();
SELECT DB_NAME();
SELECT char(212)
SELECT datename(month, convert(datetime,'2005-08-06'))
SELECT day('2009-01-26')
SELECT exp(8.5)




SELECT REVERSE("PLACE") FROM EMPLOYEE
SELECT getdate()
SELECT DATEADD(YY,3,'2009-01-01');
SELECT datename(month, convert(datetime,'2005-06-06'))
SELECT day('2009-01-05')
SELECT round(15.783, 2)

SELECT Count(*) AS Distinctvalue FROM (SELECT DISTINCT place  FROM employee);



SELECT name,firstname,place,lastname from EMPLOYEE
full join Persons on EMPLOYEE.ID=Persons.EID;

select*from employee
select*from persons

SELECT *
FROM employee
WHERE ID = ALL (SELECT name  FROM persons WHERE Age>25);

SELECT*FROM employee
WHERE id = ANY (select name from  persons where age between 1 and 25);


select*from products
INSERT INTO products(pid,pname,pdesc,price) VALUES(20,'ball','play',100);

select * from employee where AGE = (select age from employee where NAME = 'KUMAR')
select * from employee where PLACE in ('MADURAI', 'CHENNAI')

SELECT * FROM EMPLOYEE WHERE PLACE IN ( SELECT PLACE FROM EMPLOYEE WHERE NAME IN ( 'SHIVA', 'PRAVEEN') )


select distinct* from  employee where AGE>21
select REVERSE ("PLACE") from employee; 
select LTRIM ('           hai') as trimmed    
 
select len('world') 'lengthofstring';

select CHAR(65)
select RIGHT ('computercenter',5)
select left ('computercenter',8)

select Dateadd (yy,5,'2002-02-05');
select datename (month, convert(datetime,'2005-06-06'));
SELECT datename(month, convert(datetime,'2005-08-06'))
SELECT day('2009-01-26')
select GETDATE()
select DAY('2009-05-26');

select CEILING(20.1);
select ROUND(20.1, 1);
select FLOOR(20.60);
select EXP(4.3)
select POWER(5,4)

select ROUND(12.5678,2)
select round (1234.567,1)
select round (1234.567,0)
select round (1234.567,-1)
select round (1234.567,-2)
select round (2499.567,-3)
use master ;